#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process.
# Requirements:
# You must use kill

# pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# terminate the infinite process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
